import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/NavBar";
import PoppingImportantDates from "@/components/PopImportantDates";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning className="h-full">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground h-full min-h-screen flex flex-col`}>
				<ThemeProvider
					// attribute tells to save the theme in the class attribute (document.documentElement) which is <html> element!
					// to powoduje ze zmiana w setterze zmienia kolor strony
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					<NavBar />
					<div className="ml-[24px]">
						<PoppingImportantDates />
					</div>
					<div className="flex-1 flex flex-col min-h-0">{children}</div>
				</ThemeProvider>
			</body>
		</html>
	);
}



/* REFACTOR IDEA

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/NavBar";
import PoppingImportantDates from "@/components/PopImportantDates";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground h-screen flex flex-col`}>
				<ThemeProvider
					// attribute tells to save the theme in the class attribute (document.documentElement) which is <html> element!
					// to powoduje ze zmiana w setterze zmienia kolor strony
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					<div className="flex-[0.5] border-b">
						<NavBar />
					</div>

					<main className="flex-[9.5] overflow-y-auto p-4">
						<div className="ml-[24px]">
							<PoppingImportantDates />
						</div>

						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	);
}

*/